import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "en" | "ru";

const translations = {
  en: {
    // Landing
    neuropath: "neurotrack",
    menu: "Menu",
    heroLine1: "Advancing the",
    heroLine2: "spirit",
    heroLine3: "of neural AI",
    startJourney: "Start Your Journey",
    symptomTracking: "Symptom Tracking",
    aiAdvisor: "AI Advisor",
    treatmentGuide: "Treatment Guide",
    ourMission: "OUR MISSION",
    missionQuote: "We",
    missionImagined: "imagined",
    missionMiddle: "a world where no patient faces this",
    missionAlone: "alone.",
    drName: "DR. SARAH CHEN",
    joinEcosystem: "Join our ecosystem",
    joinDesc: "Connecting patients, caregivers and neurologists in one unified platform.",
    aiProcessing: "AI Processing",
    aiProcessingDesc: "Real-time neural analysis powered by advanced machine learning models.",
    careArchive: "Care Archive",
    careArchiveDesc: "Comprehensive treatment history and care documentation at your fingertips.",
    neuralMonitoring: "Advanced Neural Monitoring",
    neuralMonitoringDesc: "Tracking tremors and gait patterns with clinical-grade precision.",

    // Auth
    welcomeBack: "Welcome back",
    createAccount: "Create account",
    signInDesc: "Sign in to your NeuroTrack account",
    signUpDesc: "Start your neural health journey",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    signUp: "Sign up",
    createAccountBtn: "Create Account",
    pleaseWait: "Please wait...",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    continueGuest: "Continue as Guest",
    or: "or",

    // Dashboard
    assessmentHub: "Assessment",
    hub: "Hub",
    welcomeBackUser: "Welcome back,",
    guestMessage: "You're browsing as a guest — results won't be saved",
    takeTest: "Take a Test",
    recentResults: "Recent Results",
    noResults: "No test results yet. Take your first test above!",
    signOut: "Sign Out",
    exit: "Exit",
    signUpToSave: "Sign up to save results",
    risk: "risk",
    startTest: "Start test",

    // Tests
    spiralDrawing: "Spiral Drawing",
    spiralDesc: "Draw a spiral to assess tremor",
    voiceAnalysis: "Voice Analysis",
    voiceDesc: "Record your voice for analysis",
    symptoms: "Symptoms",
    symptomsDesc: "Answer screening questions",
    fingerTapping: "Finger Tapping",
    tappingDesc: "Tap to measure motor speed",
    back: "Back",
    clear: "Clear",
    analyzeDrawing: "Analyze Drawing",
    analyzing: "Analyzing...",
    drawMore: "Draw more",
    drawMoreDesc: "Please draw a more complete spiral",
    aiAnalysis: "AI Analysis",
    recommendations: "Recommendations",
    disclaimer: "⚠ This is a screening tool only. Please consult a neurologist for diagnosis.",

    // Spiral
    spiralTitle: "Spiral",
    spiralSubtitle: "Drawing",
    spiralTestLabel: "Test",
    spiralInstructions: "Draw a spiral starting from the center. The AI will analyze your motor control patterns.",

    // Voice
    voiceTitle: "Voice",
    voiceSubtitle: "Analysis",
    voiceInstructions: "Record yourself speaking for at least 10 seconds. Read aloud or describe your day.",
    tapToRecord: "Tap to start recording",
    recording: "Recording...",
    recorded: "Recorded",
    analyzeVoice: "Analyze Voice",
    micDenied: "Microphone access denied",
    micDeniedDesc: "Please allow microphone access to use this test.",

    // Symptoms
    symptomTitle: "Symptom",
    symptomSubtitle: "Questionnaire",
    symptomInstructions: "Answer each question based on your experience over the past month.",
    analyzeResponses: "Analyze Responses",
    never: "Never",
    rarely: "Rarely",
    sometimes: "Sometimes",
    often: "Often",
    always: "Always",

    // Symptom questions
    q_tremor: "Do you experience trembling or shaking in your hands, arms, legs, jaw, or head while at rest?",
    q_slowness: "Have you noticed slowness in your everyday movements (e.g., buttoning a shirt, eating)?",
    q_stiffness: "Do you experience stiffness or rigidity in your limbs or trunk?",
    q_balance: "Do you have difficulty with balance or have you had unexplained falls?",
    q_handwriting: "Has your handwriting become smaller or more cramped over time?",
    q_smell: "Have you noticed a reduced sense of smell?",
    q_sleep: "Do you act out dreams during sleep (kicking, punching, or falling out of bed)?",
    q_constipation: "Do you experience frequent constipation not explained by diet or medication?",
    q_voice: "Have others told you your voice has become softer or more monotone?",
    q_facial: "Have people commented that you look serious, depressed, or have a 'masked' face even when not in a bad mood?",
    q_dizziness: "Do you feel dizzy or faint when standing up from sitting or lying down?",
    q_posture: "Do you notice yourself stooping, leaning, or slouching when you stand?",

    // Tapping
    tappingTitle: "Finger",
    tappingSubtitle: "Tapping",
    tappingTestLabel: "Test",
    tappingInstructions: "Tap the button as fast and steadily as you can for 15 seconds.",
    taps: "taps",
    tapsIn: "taps in",
    seconds: "seconds",
    tapsSec: "taps/sec",
    tryAgain: "Try Again",
    analyze: "Analyze",
    notEnoughTaps: "Not enough taps",
    notEnoughTapsDesc: "Please tap more during the test",

    // Menu
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    darkGlass: "Dark Glass",
    whitePurple: "White & Purple",
    oceanBlue: "Ocean Blue",
    roseGold: "Rose Gold",
    forestGreen: "Forest Green",
    english: "English",
    russian: "Русский",
    close: "Close",

    // Learn
    learnTitle: "Learn",
    learnSubtitle: "About Parkinson's",
    learnIntro: "Educational resources to understand Parkinson's disease better.",
    learnArticles: "KEY TOPICS",
    learnWhat: "What is Parkinson's?",
    learnWhatDesc: "Parkinson's disease is a progressive nervous system disorder that affects movement. It develops gradually, sometimes starting with a barely noticeable tremor in just one hand.",
    learnSymptoms: "Early Symptoms",
    learnSymptomsDesc: "Tremors, slowed movement, rigid muscles, impaired posture and balance, loss of automatic movements, speech changes, and writing changes.",
    learnCauses: "Causes & Risk Factors",
    learnCausesDesc: "Certain neurons in the brain gradually break down or die. Genetics, environmental triggers, age, and sex all play roles in risk.",
    learnTreatment: "Treatment Options",
    learnTreatmentDesc: "While there's no cure, medications can significantly improve symptoms. Physical therapy, exercise, and deep brain stimulation are also options.",
    learnLiving: "Living With Parkinson's",
    learnLivingDesc: "Regular exercise, balanced diet, fall prevention, and support groups can greatly improve quality of life for those with Parkinson's.",
    learnResearch: "Latest Research",
    learnResearchDesc: "Scientists are studying biomarkers, gene therapy, stem cells, and new medications to better understand and treat Parkinson's disease.",
    learnSigns: "Warning Signs",
    learnSignsDesc: "Key early warning signs that may indicate the onset of Parkinson's disease, often appearing years before motor symptoms.",
    learnWhatDetail: "Parkinson's disease (PD) is a chronic, progressive neurodegenerative disorder that primarily affects the motor system. It is caused by the loss of dopamine-producing neurons in a region of the brain called the substantia nigra.\n\nDopamine is a neurotransmitter that plays a crucial role in coordinating smooth, purposeful muscle movement. When approximately 60–80% of these neurons are damaged, the hallmark motor symptoms of Parkinson's begin to appear.\n\n## How It Progresses\n\nParkinson's is typically divided into five stages (Hoehn & Yahr scale):\n\n• Stage 1: Mild symptoms on one side of the body only. Tremor in one hand, changes in posture or walking.\n• Stage 2: Symptoms on both sides. Walking and balance may be affected, but the person can still live independently.\n• Stage 3: Loss of balance and slowness of movement. Falls become more common. Still independent but daily activities are impaired.\n• Stage 4: Severe symptoms. The person may need a walker. Cannot live alone safely.\n• Stage 5: Wheelchair-bound or bedridden. Round-the-clock care is required.\n\n## Key Facts\n\n• Affects roughly 10 million people worldwide\n• Second most common neurodegenerative disease after Alzheimer's\n• Average age of onset is 60, but early-onset PD can begin before 50\n• Men are 1.5× more likely to develop PD than women\n• The disease itself is not fatal, but complications can be serious",
    learnSymptomsDetail: "Parkinson's symptoms are divided into motor and non-motor categories. Motor symptoms are the most visible, but non-motor symptoms can appear 10–20 years earlier.\n\n## Motor Symptoms\n\n• Tremor: Rhythmic shaking, usually starting in a hand or fingers. The classic 'pill-rolling' tremor occurs at rest.\n• Bradykinesia (slowness): Movements become slow and small. Simple tasks like buttoning a shirt take much longer.\n• Rigidity: Stiffness in the limbs and trunk. Muscles feel tight and resist movement.\n• Postural instability: Impaired balance and coordination, leading to falls.\n• Gait changes: Shuffling steps, freezing of gait, reduced arm swing while walking.\n\n## Non-Motor Symptoms\n\n• Loss of smell (hyposmia) — often one of the earliest signs\n• Sleep disorders — REM sleep behavior disorder, insomnia, excessive daytime sleepiness\n• Constipation and other digestive issues\n• Depression and anxiety — can precede motor symptoms by years\n• Cognitive changes — difficulty with planning, multitasking, memory\n• Fatigue — overwhelming tiredness unrelated to physical activity\n• Urinary problems — urgency, frequency\n• Low blood pressure when standing (orthostatic hypotension)\n• Pain and tingling sensations",
    learnCausesDetail: "The exact cause of Parkinson's disease remains unknown, but research points to a combination of genetic and environmental factors.\n\n## Genetics\n\n• About 10–15% of cases have a clear genetic link\n• Mutations in genes like LRRK2, PARK7, PINK1, PRKN, and SNCA are associated with PD\n• Having a first-degree relative with PD increases risk by 2–3×\n• The GBA gene (linked to Gaucher disease) is the most common genetic risk factor\n\n## Environmental Factors\n\n• Exposure to pesticides (paraquat, rotenone) increases risk\n• Rural living and well-water drinking have been associated with higher rates\n• Head injuries (traumatic brain injury) may increase risk\n• Interestingly, caffeine and smoking are associated with lower risk (though smoking is not recommended)\n\n## What Happens in the Brain\n\n• Lewy bodies — abnormal clumps of the protein alpha-synuclein — accumulate in neurons\n• These Lewy bodies disrupt normal cell function and eventually cause cell death\n• The spread of alpha-synuclein may follow a pattern from the gut and brainstem upward (Braak hypothesis)\n• Neuroinflammation and mitochondrial dysfunction also contribute to neuronal damage",
    learnTreatmentDetail: "While there is currently no cure for Parkinson's, many treatments can effectively manage symptoms and improve quality of life.\n\n## Medications\n\n• Levodopa/Carbidopa (Sinemet): The gold standard. Levodopa converts to dopamine in the brain. Most effective for motor symptoms.\n• Dopamine agonists (pramipexole, ropinirole): Mimic dopamine effects. Used early on or with levodopa.\n• MAO-B inhibitors (selegiline, rasagiline): Block enzyme that breaks down dopamine.\n• COMT inhibitors (entacapone): Extend the effect of levodopa.\n• Amantadine: Can reduce dyskinesias (involuntary movements from long-term levodopa use).\n• Anticholinergics: May help tremor but have cognitive side effects.\n\n## Surgical Options\n\n• Deep Brain Stimulation (DBS): Electrodes implanted in the brain deliver electrical pulses. Can dramatically reduce tremor, rigidity, and dyskinesias.\n• Focused Ultrasound: Non-invasive technique to treat tremor by targeting specific brain areas.\n\n## Therapies\n\n• Physical therapy — improves mobility, balance, and flexibility\n• Occupational therapy — helps maintain independence in daily tasks\n• Speech therapy — addresses voice softness and swallowing difficulties\n• Exercise — regular aerobic exercise has been shown to slow symptom progression. Boxing, cycling, dancing, and tai chi are particularly beneficial.",
    learnSignsDetail: "Recognizing early warning signs of Parkinson's can lead to earlier diagnosis and better management. These signs can appear years or even decades before the classic tremor.\n\n## The 10 Early Warning Signs\n\n• Loss of smell: Difficulty smelling foods like bananas, pickles, or licorice. One of the earliest signs.\n• Tremor: Slight shaking in your finger, thumb, hand, chin, or lip while at rest.\n• Small handwriting: Your handwriting has become much smaller than it used to be (micrographia).\n• Sleep problems: Thrashing, kicking, or falling out of bed during deep sleep (REM behavior disorder).\n• Trouble moving or walking: Stiffness in arms, legs, or body. Feet feel 'stuck to the floor.'\n• Constipation: Straining to move bowels without dietary explanation.\n• Soft or low voice: Others tell you your voice is very soft or hoarse.\n• Masked face: You look serious, depressed, or angry even when not in a bad mood.\n• Dizziness or fainting: Regular dizziness when standing up from sitting.\n• Stooping or hunching: You're no longer standing as straight as you used to.\n\n## When to See a Doctor\n\nIf you notice two or more of these signs, it's worth discussing them with a neurologist. Early diagnosis allows for earlier treatment, better symptom management, and access to clinical trials.\n\n## Important Note\n\nHaving one or two of these signs does not necessarily mean you have Parkinson's. Many conditions can cause similar symptoms. Only a qualified neurologist can make a diagnosis.",
    learnLivingDetail: "Living well with Parkinson's is absolutely possible. Many people lead active, fulfilling lives for years after diagnosis.\n\n## Exercise\n\n• Exercise is the single most important thing you can do. Research shows it can slow disease progression.\n• Aim for 150 minutes of moderate exercise per week.\n• Best activities: cycling, boxing (non-contact), dancing, swimming, tai chi, yoga.\n• Exercise improves balance, flexibility, strength, mood, and sleep.\n\n## Diet & Nutrition\n\n• Mediterranean diet is recommended — rich in fruits, vegetables, whole grains, fish, and olive oil.\n• Increase fiber and water intake to manage constipation.\n• Protein can interfere with levodopa absorption — some patients benefit from taking medication 30 minutes before meals.\n• Stay hydrated — dehydration can worsen symptoms.\n• Antioxidant-rich foods (berries, nuts, leafy greens) may support brain health.\n\n## Mental Health\n\n• Depression affects up to 50% of people with PD — it's a symptom, not just a reaction.\n• Seek counseling or therapy. Cognitive behavioral therapy (CBT) is effective.\n• Stay socially connected — join support groups, maintain friendships.\n• Mindfulness and meditation can reduce anxiety and improve well-being.\n\n## Practical Tips\n\n• Simplify your home to prevent falls — remove rugs, add grab bars, improve lighting.\n• Use adaptive tools — large-handle utensils, button hooks, voice-activated devices.\n• Plan activities during your 'on' times when medication is working best.\n• Keep a symptom diary to help your doctor optimize treatment.",
    learnResearchDetail: "Parkinson's research is advancing rapidly, with several promising areas that could transform treatment.\n\n## Gene Therapy\n\n• Researchers are developing viral vectors to deliver protective genes directly into brain cells.\n• Clinical trials are exploring ways to boost dopamine production genetically.\n• CRISPR gene editing shows promise for correcting PD-related mutations.\n\n## Stem Cell Therapy\n\n• Scientists are growing dopamine neurons from stem cells and transplanting them into the brain.\n• Clinical trials in Japan, Sweden, and the US are showing encouraging early results.\n• The goal is to replace lost neurons and restore natural dopamine production.\n\n## Alpha-Synuclein Targeting\n\n• Immunotherapy approaches aim to clear toxic alpha-synuclein protein clumps.\n• Several antibody-based treatments are in clinical trials.\n• Vaccines to prevent alpha-synuclein aggregation are being developed.\n\n## Biomarkers\n\n• A breakthrough blood test can now detect misfolded alpha-synuclein years before symptoms appear.\n• Skin biopsy tests and spinal fluid analysis can aid early diagnosis.\n• AI and machine learning are being used to detect early PD from voice, gait, and typing patterns.\n\n## Neuroprotective Strategies\n\n• GLP-1 receptor agonists (diabetes drugs) have shown neuroprotective effects in PD trials.\n• High-dose exercise is being studied as a neuroprotective intervention.\n• Researchers are exploring the gut-brain connection — gut microbiome changes may influence PD progression.",
    learnDisclaimer: "This information is for educational purposes only and is not a substitute for professional medical advice. Always consult a qualified healthcare provider.",
    resourceMayo: "Comprehensive medical information on Parkinson's symptoms, causes, and treatment.",
    resourceNIH: "National Institute of Neurological Disorders and Stroke — research and resources.",
    learnVideos: "VIDEO RESOURCES",
    videoWhat: "What is Parkinson's Disease?",
    videoSymptoms: "Early Signs & Symptoms",
    videoExercise: "Exercise for Parkinson's",
    videoDiet: "Diet & Nutrition Tips",
    learnResources: "TRUSTED RESOURCES",
    resourcePF: "Leading organization for Parkinson's research and support.",
    resourceMJF: "Funding research to find a cure for Parkinson's disease.",
    resourceWHO: "Global health information on Parkinson's disease.",
    learnPage: "Learn",
    gamesPage: "Games",

    // Games
    gamesTitle: "Detection",
    gamesSubtitle: "Games",
    gamesIntro: "Fun interactive games that can help screen for motor and cognitive patterns associated with Parkinson's.",
    gameReaction: "Reaction",
    gameMemory: "Memory",
    gameBalance: "Balance",
    reactionTap: "Tap to start — wait for green",
    reactionWait: "Wait for green...",
    reactionNow: "TAP NOW!",
    reactionEarly: "Too early!",
    reactionTapAgain: "Tap to try again",
    reactionAvg: "Average",
    reactionTrials: "trials",
    reactionGood: "Good reaction time",
    reactionNormal: "Normal range",
    reactionSlow: "Slower than average — consider a full assessment",
    memoryStart: "Tap to start memory game",
    memoryLevel: "Level",
    memorySeqLen: "Sequence",
    memoryCorrect: "Correct! Next level...",
    memoryWrong: "Game over",
    memoryGood: "Strong memory performance",
    memoryNormal: "Normal range",
    memoryLow: "Below average — consider a cognitive assessment",
    memoryWatch: "Watch the sequence...",
    memoryRepeat: "Now repeat the sequence!",
    balanceStart: "Tap to start balance test",
    balanceHold: "Hold your phone still for 10 seconds",
    balanceHolding: "Hold still...",
    balanceKeep: "Keep the phone as steady as possible",
    balanceScore: "Average motion deviation",
    balanceNoData: "No motion data — try on a mobile device",
    balanceSteady: "Very steady — good result",
    balanceModerate: "Some movement detected",
    balanceUnsteady: "Significant movement — consider further assessment",
    balanceNotSupported: "Motion sensor not available",
    balanceDesktop: "This test works best on a mobile device with motion sensors.",
  },
  ru: {
    neuropath: "нейротрек",
    menu: "Меню",
    heroLine1: "Продвигая",
    heroLine2: "дух",
    heroLine3: "нейронного ИИ",
    startJourney: "Начать путь",
    symptomTracking: "Отслеживание",
    aiAdvisor: "ИИ-Консультант",
    treatmentGuide: "Руководство",
    ourMission: "НАША МИССИЯ",
    missionQuote: "Мы",
    missionImagined: "представили",
    missionMiddle: "мир, где ни один пациент не сталкивается с этим",
    missionAlone: "в одиночку.",
    drName: "Д-Р САРА ЧЕН",
    joinEcosystem: "Присоединяйтесь",
    joinDesc: "Объединяем пациентов, опекунов и неврологов на единой платформе.",
    aiProcessing: "ИИ-Обработка",
    aiProcessingDesc: "Нейронный анализ в реальном времени на основе машинного обучения.",
    careArchive: "Архив лечения",
    careArchiveDesc: "Полная история лечения и документация под рукой.",
    neuralMonitoring: "Нейромониторинг",
    neuralMonitoringDesc: "Отслеживание тремора и походки с клинической точностью.",

    welcomeBack: "С возвращением",
    createAccount: "Создать аккаунт",
    signInDesc: "Войдите в ваш аккаунт NeuroTrack",
    signUpDesc: "Начните путь к здоровью",
    fullName: "Полное имя",
    email: "Эл. почта",
    password: "Пароль",
    signIn: "Войти",
    signUp: "Регистрация",
    createAccountBtn: "Создать аккаунт",
    pleaseWait: "Подождите...",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    continueGuest: "Продолжить как гость",
    or: "или",

    assessmentHub: "Центр",
    hub: "Оценки",
    welcomeBackUser: "С возвращением,",
    guestMessage: "Вы гость — результаты не сохраняются",
    takeTest: "Пройти тест",
    recentResults: "Последние результаты",
    noResults: "Результатов пока нет. Пройдите первый тест!",
    signOut: "Выйти",
    exit: "Выход",
    signUpToSave: "Зарегистрируйтесь для сохранения",
    risk: "риск",
    startTest: "Начать тест",

    spiralDrawing: "Рисование спирали",
    spiralDesc: "Нарисуйте спираль для оценки тремора",
    voiceAnalysis: "Анализ голоса",
    voiceDesc: "Запишите голос для анализа",
    symptoms: "Симптомы",
    symptomsDesc: "Ответьте на вопросы",
    fingerTapping: "Постукивание",
    tappingDesc: "Постукивайте для оценки моторики",
    back: "Назад",
    clear: "Очистить",
    analyzeDrawing: "Анализировать",
    analyzing: "Анализ...",
    drawMore: "Нарисуйте больше",
    drawMoreDesc: "Нарисуйте более полную спираль",
    aiAnalysis: "Анализ ИИ",
    recommendations: "Рекомендации",
    disclaimer: "⚠ Это инструмент скрининга. Проконсультируйтесь с неврологом.",

    spiralTitle: "Рисование",
    spiralSubtitle: "Спирали",
    spiralTestLabel: "Тест",
    spiralInstructions: "Нарисуйте спираль из центра. ИИ проанализирует ваш моторный контроль.",

    voiceTitle: "Анализ",
    voiceSubtitle: "Голоса",
    voiceInstructions: "Запишите речь минимум 10 секунд. Читайте вслух или расскажите о дне.",
    tapToRecord: "Нажмите для записи",
    recording: "Запись...",
    recorded: "Записано",
    analyzeVoice: "Анализ голоса",
    micDenied: "Доступ к микрофону запрещён",
    micDeniedDesc: "Разрешите доступ к микрофону.",

    symptomTitle: "Опросник",
    symptomSubtitle: "Симптомов",
    symptomInstructions: "Ответьте на вопросы по опыту последнего месяца.",
    analyzeResponses: "Анализировать ответы",
    never: "Никогда",
    rarely: "Редко",
    sometimes: "Иногда",
    often: "Часто",
    always: "Всегда",

    q_tremor: "Вы испытываете дрожь в руках, ногах, челюсти или голове в покое?",
    q_slowness: "Замечаете ли вы замедление повседневных движений (застёгивание, еда)?",
    q_stiffness: "Испытываете ли скованность или ригидность в конечностях?",
    q_balance: "Есть ли трудности с равновесием или необъяснимые падения?",
    q_handwriting: "Стал ли почерк мельче или теснее со временем?",
    q_smell: "Заметили ли снижение обоняния?",
    q_sleep: "Разыгрываете ли сны во сне (пинки, удары, падения с кровати)?",
    q_constipation: "Испытываете ли частые запоры, не связанные с диетой?",
    q_voice: "Говорили ли вам, что голос стал тише или монотоннее?",
    q_facial: "Замечали ли, что выглядите серьёзно или подавленно без причины?",
    q_dizziness: "Кружится ли голова при вставании?",
    q_posture: "Замечаете ли сутулость при стоянии?",

    tappingTitle: "Тест",
    tappingSubtitle: "Постукивания",
    tappingTestLabel: "",
    tappingInstructions: "Постукивайте по кнопке быстро и ритмично 15 секунд.",
    taps: "нажатий",
    tapsIn: "нажатий за",
    seconds: "секунд",
    tapsSec: "нажатий/сек",
    tryAgain: "Ещё раз",
    analyze: "Анализ",
    notEnoughTaps: "Мало нажатий",
    notEnoughTapsDesc: "Постукивайте чаще во время теста",

    settings: "Настройки",
    language: "Язык",
    theme: "Тема",
    darkGlass: "Тёмное стекло",
    whitePurple: "Белая и фиолетовая",
    oceanBlue: "Океанская синева",
    roseGold: "Розовое золото",
    forestGreen: "Лесная зелень",
    english: "English",
    russian: "Русский",
    close: "Закрыть",

    learnTitle: "Изучите",
    learnSubtitle: "Паркинсона",
    learnIntro: "Образовательные ресурсы для понимания болезни Паркинсона.",
    learnArticles: "КЛЮЧЕВЫЕ ТЕМЫ",
    learnWhat: "Что такое Паркинсон?",
    learnWhatDesc: "Болезнь Паркинсона — прогрессирующее заболевание нервной системы, влияющее на движение. Развивается постепенно, иногда начинаясь с едва заметного тремора.",
    learnSymptoms: "Ранние симптомы",
    learnSymptomsDesc: "Тремор, замедление движений, ригидность мышц, нарушение осанки и равновесия, изменение речи и почерка.",
    learnCauses: "Причины и факторы риска",
    learnCausesDesc: "Определённые нейроны мозга постепенно разрушаются. Генетика, окружающая среда, возраст и пол влияют на риск.",
    learnTreatment: "Варианты лечения",
    learnTreatmentDesc: "Лекарства могут значительно улучшить симптомы. Физиотерапия, упражнения и глубокая стимуляция мозга также помогают.",
    learnLiving: "Жизнь с Паркинсоном",
    learnLivingDesc: "Регулярные упражнения, сбалансированное питание и группы поддержки значительно улучшают качество жизни.",
    learnResearch: "Последние исследования",
    learnResearchDesc: "Учёные изучают биомаркеры, генную терапию, стволовые клетки и новые лекарства.",
    learnVideos: "ВИДЕОРЕСУРСЫ",
    videoWhat: "Что такое болезнь Паркинсона?",
    videoSymptoms: "Ранние признаки и симптомы",
    videoExercise: "Упражнения при Паркинсоне",
    videoDiet: "Диета и питание",
    learnResources: "ПРОВЕРЕННЫЕ РЕСУРСЫ",
    resourcePF: "Ведущая организация по исследованию Паркинсона.",
    resourceMJF: "Финансирование исследований для поиска лечения.",
    resourceWHO: "Глобальная информация о болезни Паркинсона.",
    learnPage: "Обучение",
    gamesPage: "Игры",

    gamesTitle: "Игры",
    gamesSubtitle: "Диагностики",
    gamesIntro: "Интерактивные игры для скрининга моторных и когнитивных паттернов.",
    gameReaction: "Реакция",
    gameMemory: "Память",
    gameBalance: "Баланс",
    reactionTap: "Нажмите — ждите зелёный",
    reactionWait: "Ждите зелёный...",
    reactionNow: "НАЖМИТЕ!",
    reactionEarly: "Слишком рано!",
    reactionTapAgain: "Нажмите снова",
    reactionAvg: "Среднее",
    reactionTrials: "попыток",
    reactionGood: "Хорошее время реакции",
    reactionNormal: "Нормальный диапазон",
    reactionSlow: "Медленнее среднего — рекомендуется обследование",
    memoryStart: "Нажмите для начала",
    memoryLevel: "Уровень",
    memorySeqLen: "Последовательность",
    memoryCorrect: "Верно! Следующий уровень...",
    memoryWrong: "Конец игры",
    memoryGood: "Сильная память",
    memoryNormal: "Нормальный диапазон",
    memoryLow: "Ниже среднего — рекомендуется оценка",
    memoryWatch: "Запомните последовательность...",
    memoryRepeat: "Повторите последовательность!",
    balanceStart: "Нажмите для теста баланса",
    balanceHold: "Держите телефон неподвижно 10 секунд",
    balanceHolding: "Держите...",
    balanceKeep: "Держите телефон максимально ровно",
    balanceScore: "Среднее отклонение",
    balanceNoData: "Нет данных — попробуйте на мобильном",
    balanceSteady: "Очень устойчиво — хороший результат",
    balanceModerate: "Обнаружено некоторое движение",
    balanceUnsteady: "Значительное движение — рекомендуется обследование",
    balanceNotSupported: "Датчик движения недоступен",
    balanceDesktop: "Этот тест лучше работает на мобильном устройстве.",
  },
};

type Translations = Record<keyof typeof translations.en, string>;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
});

export const LangProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("neuropath-lang");
    return (saved === "ru" ? "ru" : "en") as Lang;
  });

  const handleSetLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem("neuropath-lang", l);
  };

  return (
    <LangContext.Provider value={{ lang, setLang: handleSetLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
